# Deployment do Backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: barbarasousilva/healthmed-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configmap
            - secretRef:
                name: secrets
---
# Deployment do Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: barbarasousilva/healthmed-frontend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configmap
